import initScrollSmooth from './modules/scroll-smooth.js';
import initAnimationScroll from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion.js';
import iniTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimais from './modules/fetch-animais.js';

initScrollSmooth();
initAnimationScroll();
initAccordion();
iniTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();